Make secret job fail when not logged in
* Also replace enterprise-logs cluster with helm installed version

diff --git a/tools/dev/k3d/Makefile b/tools/dev/k3d/Makefile
--- a/tools/dev/k3d/Makefile
+++ b/tools/dev/k3d/Makefile
@@ -1,4 +1,5 @@
-.PHONY: loki-distributed down add-repos update-repos prepare prepare-gel build-latest-image
+.PHONY: loki-distributed enterprise-logs helm-cluster down add-repos update-repos prepare prepare-gel
+.PHONY: build-latest-image helm-install-enterprise-logs helm-upgrade-enterprise-logs helm-uninstall-enterprise-logs
 
 IMAGE_TAG := $(shell ../../../tools/image-tag)
 EXISTING_REGISTRY_PORT := $(shell k3d registry list -o json | jq -r '.[] | select(.name == "k3d-grafana") | .portMappings."5000/tcp" | .[0].HostPort')
@@ -10,29 +11,20 @@ loki-distributed: prepare build-latest-image
 	sleep 5
 	tk apply --ext-str registry="k3d-grafana:$(REGISTRY_PORT)" environments/loki-distributed
 
-enterprise-logs: prepare-gel
-	$(CURDIR)/scripts/create_cluster.sh enterprise-logs $(REGISTRY_PORT)
-	# wait 5s for the cluster to be ready
-	sleep 5
-	$(MAKE) -C $(CURDIR) apply-enterprise-logs
+enterprise-logs: prepare-gel helm-cluster
+	$(MAKE) -C $(CURDIR) helm-install-enterprise-logs
 
 helm-cluster: prepare
-	ls -la $(CURDIR)
-	ls -la $(CURDIR)/scripts
 	$(CURDIR)/scripts/create_cluster.sh helm-cluster $(REGISTRY_PORT)
 	# wait 5s for the cluster to be ready
 	sleep 5
 	$(MAKE) -C $(CURDIR) apply-helm-cluster
-
-apply-enterprise-logs:
-	tk apply --ext-str registry="k3d-grafana:$(REGISTRY_PORT)" environments/enterprise-logs
 
 apply-helm-cluster:
 	tk apply --ext-str registry="k3d-grafana:$(REGISTRY_PORT)" environments/helm-cluster
 
 down:
 	k3d cluster delete loki-distributed
-	k3d cluster delete enterprise-logs
 	k3d cluster delete helm-cluster
 
 add-repos:
@@ -66,11 +58,20 @@ secrets: secrets/grafana.jwt secrets/gel.jwt
 
 secrets/grafana.jwt:
 	mkdir -p secrets/
-	op document get "loki/grafana.jwt" --output=$(CURDIR)/secrets/grafana.jwt
+	op document get "loki/grafana.jwt" --output=$(CURDIR)/secrets/grafana.jwt || rm -f $(CURDIR)/secrets/grafana.jwt
+	@if ! test -s "$(CURDIR)/secrets/grafana.jwt"; then \
+		echo "Failed to fetch Grafana license from 1Password, are you logged in?"; \
+		rm -f $(CURDIR)/secrets/grafana.jwt; \
+		exit 1; \
+	fi
 
 secrets/gel.jwt:
 	mkdir -p secrets/
-	op document get "loki/gel.jwt" --output=$(CURDIR)/secrets/gel.jwt
+	op document get "loki/gel.jwt" --output=$(CURDIR)/secrets/gel.jwt || rm -f $(CURDIR)/secrets/gel.jwt
+	@if ! test -s "$(CURDIR)/secrets/gel.jwt"; then \
+		echo "Failed to fetch GEL license from 1Password, are you logged in?"; \
+		exit 1; \
+	fi
 
 prepare: create-registry update-repos
 prepare-gel: prepare secrets
