ci: Update workflows [release-3.6.x] (#22519)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,7 +6,7 @@ env:
   GITHUB_APP: "loki-gh-app"
   IMAGE_PREFIX: "grafana"
   PUBLISH_TO_GCS: false
-  RELEASE_LIB_REF: "a3091f6507615a4646e399870071074d66c30826"
+  RELEASE_LIB_REF: "ab3eb3e72e185daa72c9a70c589bde074faaf0dc"
   RELEASE_REPO: "grafana/loki"
 jobs:
   createRelease:
@@ -95,13 +95,20 @@ jobs:
       name: "create release"
       run: |
         yarn install
-        yarn exec -- release-please github-release \
+        output=$(yarn exec -- release-please github-release \
           --draft \
           --release-type simple \
           --repo-url "${{ env.RELEASE_REPO }}" \
           --target-branch "$(echo $OUTPUTS_BRANCH | tr -d '"')" \
           --token "$(echo $OUTPUTS_TOKEN | tr -d '"')" \
-          --shas-to-tag "$(echo $OUTPUTS_PR_NUMBER | tr -d '"'):$(echo ${SHA} | tr -d '"')"
+          --shas-to-tag "$(echo $OUTPUTS_PR_NUMBER | tr -d '"'):$(echo ${SHA} | tr -d '"')" \
+          --pull-request-title-pattern "chore\${scope}: Release\${component} \${version}" \
+          --group-pull-request-title-pattern "chore\${scope}: Release\${component} \${version}")
+        echo "$output"
+        if [[ "$output" == "[]" || -z "$output" ]]; then
+          echo "::error::release-please did not create a release"
+          exit 1
+        fi
       working-directory: "lib"
     - env:
         GH_TOKEN: "${{ steps.get_github_app_token.outputs.token }}"
